language: minimal

services: 
        - docker

script:
        - docker pull olllom/coffeci-chm 
        - docker run olllom/coffeci-chm /bin/sh -c "cd /root; wget http://github.com/olllom/charmm-vs-openmm-energies/tarball/vswitch; tar xzvf master; cd O*; python run.py"

