language: minimal

services:
  - docker

before_install:
  - docker pull olllom/coffeci-chm
  - docker run --name chmtest --rm -d -i -t olllom/coffeci-chm bash
  - docker cp . chmtest:/root

script:
  - docker exec -w /root chmtest python run.py -t -v
