language: minimal

services:
  - docker

before_install:
  - docker pull olllom/coffeci-chm
  - docker run -d -p 127.0.0.1:80:4567 olllom/coffeci-chm /bin/sh -c "cd /root"
  - docker ps -a
  - docker run olllom/coffeci-chm /bin/sh -c "cd /root"

script:
    - python run.py # bundle exec rake test

      #services: 
      #        - docker
      #
      #script:
      #        - docker pull olllom/coffeci-chm 
      #        - docker run olllom/coffeci-chm /bin/sh -c "cd /root; wget http://github.com/olllom/charmm-vs-openmm-energies/tarball/vswitch; tar xzvf master; cd O*; python run.py"
      #
